### ISSUE TITLE
Any way to save to another TH wiki?

### ISSUE THREAD

**Issue by twMat** [simonbaird/tiddlyhost#102]
Related to #101 and probably also #79

I have two TH wikis. Why does it not work to save to the second wiki by merely changing the `$:/UploadURL` field value in the first wiki? (Is there perhaps some security check that matches the UploadURL the current URL?)

I.e: Is there any way to save the wiki into another TH wiki?

Background (not necessary to read): 
Jeremy just [announced](https://groups.google.com/g/tiddlywiki/c/SLpIpsIvg6Q) Community Links Aggregator and requests that we participlate with wikis that only contain the shared tiddlers. So, I'm trying to create a Save button in my regular wiki on TH that *also* saves to a second TH wiki for the community link sharing, but via a different saving filter. So I was hoping it'd be enough if my custom Save button just sets the `$:/UploadURL` and does `tm-save-wiki` again.

**Comment by simonbaird** [comment]
For the first question: I think it's because of [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing). By default, a page from aaa.tiddlyhost.com is blocked from posting to bbb.tiddlyhost.com for security reasons.

To copy content from one TiddlyWiki to another, you could download the first site, then use the "Upload" function from the Actions menu in your sites list to upload it to the second.

Currently I don't see a good solution for saving a TW in two places with a single button. I guess there could be a "Copy from" option in the Actions menu, but that's probably not what you're looking for.

**Comment by twMat** [comment]
Thanks for reply. With the "reopening" of Tiddlyspot I think it will work there at least (it did previously), and just maybe it's possible to save to the current Tiddlyhost plus a Tiddlyspot!

**Comment by simonbaird** [comment]
Well, we could write some code to do it on the server. For example, imagine if you wanted twmat.tiddlyspot.com to always be an identical mirror of twmat.tiddlyhost.com. You could configure it in settings, e.g. "This should be a a mirror of: [ --select other site--]".

I guess saving on the mirrored site would be disabled, since it would get confusing otherwise.

**Comment by simonbaird** [comment]
I'm not sure if this kind of feature would be used much by a typical user though...

**Comment by simonbaird** [comment]
I don't think this will progress any further from here. Let's close.
