### ISSUE TITLE
Support cross-site saving maybe

### ISSUE THREAD

**Issue by simonbaird** [simonbaird/tiddlyhost#119]
In #112 CORS headers were added for get requests. This issue is to consider adding sufficient CORS headers to allow cross-origin saving, and to confirm that it works.

(I think probably some testing is needed to see if the session cookie will work in this scenario.)

The need for this is perhaps not 100% clear to me. Since I expect it will never work from a file:// url, and because it's already possible to use the "Upload" button to replace a site entirely, the ability to save from one site to another by tweaking the upload URL seems like a neat trick for power users, rather than something generally useful.

**Comment by saqimtiaz** [comment]
Personally its the use case of being to save from a file:// uri that I find appealing if its possible. Otherwise I agree that this is an edge case.

I am not sure what kind of request is needed to save a TH wiki, but do note that TW has a bit of an issue which makes CORS issues more commonplace than they actually should be: https://github.com/Jermolene/TiddlyWiki5/issues/4537#issuecomment-812831186

**Comment by simonbaird** [comment]
That's interesting, thanks.

TH uploads are just a BidiX upload plugin compatible post, but with a session cookie for authentication.

**Comment by simonbaird** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials is relevant I think. See the explanations at https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS .

**Comment by simonbaird** [comment]
No plans for cross-site saving, so let's close this.
