### ISSUE TITLE
autosave revert to "Do not save changes automatically" after reload/reopen site

### ISSUE THREAD

**Issue by ccshao** [simonbaird/tiddlyhost#133]
I am new to the tiddlywiki so like asking about a stupid question. 

In my tiddlywiki file in tiddlyhost, I set the autosave to "yes", click "save changes". In this tab, it works nicely.
However, once I close and reopen my wiki, or click "perform a full refresh", the setting of autosave changed to "no".

How to permanently set the autosave to "yes"? Thanks!

**Comment by simonbaird** [comment]
Actually this is a very good question -- something I should add to the FAQ.

It's intentional that the autosave option is forced off for Tiddlyhost sites. My thinking is that performing a full upload/save on every single change could create a lot of extra load on the server. Every save requires a full upload of the entire file, so it's an expensive operation.

Maybe in future I'll look at the impact of autosave being switched on permanently, and consider if it could be okay to allow it, but right now you won't be able to do it.

**Comment by ccshao** [comment]
That is clear and understandable. Thanks!

**Comment by fmatosqg** [comment]
What I had in one of my old tiddlyspot was autosave always on, but with some smart scheduling. Like whenever there was something to be saved I'd look up the time since last upload. If less than 5 min I'd schedule it to run on 5 min mark.

You'd be able to take this further with some kind of exponential back off, starting as often as a few sec then gradually reaching 10 min.

**Comment by simonbaird** [comment]
Yeah, that would be a nice feature. I feel like it could be a TW plugin or even a TW core feature to enhance autosave behavior so supports an optional backoff time, rather than something specific to Tiddlyhost.

**Comment by GatesDA** [comment]
Is autosave feasible for external-core TiddlyWikis, given their drastic filesize reduction?

**Comment by simonbaird** [comment]
@GatesDA Yeah, good idea. I pushed an update just now to enable autosave for external core TW.
