### ISSUE TITLE
Support using external-js version of TiddlyWiki

### ISSUE THREAD

**Issue by simonbaird** [simonbaird/tiddlyhost#171]
I'm not sure how it works, but it seems like it could be useful for Tiddlyhost. See https://github.com/Jermolene/TiddlyWiki5/pull/5570 .

Update Dec 6, 2022: This has been demonstrated by @Telumire at https://tiddlywiki-5-2-4-prerelease-external-js.tiddlyhost.com/ and it works great. I changed the title from "Investigate..." to "Support...". See also the later discussion in this issue.

**Comment by pmario** [comment]
It splits the wiki into 2 elements. The index.html data section + plugins and the tiddlywikicore-<version>.js which can be cached by the browser. 

I think it can safe you some outgoing bandwidth and some harddisk space if the core is "hardlinked" into the wiki directory. 

I use it with a local WebDav setup. ... 

There is a  possibility to move plugins to the core-file but that wasn't part of the PR. If the plugins are part of the core-file, it would be relatively easy to update the core, by swtching only one hard-link. + the reference in the index.html

**Comment by simonbaird** [comment]
Cool, thanks. It seems ideal for Tiddlyhost. One challenge will be making sure you can still download a working TW file. I guess Tiddlyhost would need to be able to reassemble a standalone TW file for downloading.

**Comment by pmario** [comment]
I think it should be enough to have a button similar to the "Download Empty" but with a filter that makes it a "Download Wiki" button.

**Comment by simonbaird** [comment]
Reading through https://github.com/Jermolene/TiddlyWiki5/pull/5570 it seems like the external js version isn't going to be supported long term. So this might be a dead end.

I'd still like to learn more about it though. Perhaps we could use an unsupported version. I'm interested in reducing the amount of data that needs to be sent for a Tiddlyhost save. Currently it's a lot because in includes all of core.js, so saving is quite slow.

**Comment by pmario** [comment]
The PR didn't introduce a technical problem. It did introduce a philosophical one. Jeremy didn't like, that the mechanism is "too visible" see: https://github.com/Jermolene/TiddlyWiki5/pull/5570#issuecomment-892127428  and it did add a "download" button to the PageToolbar section, which is off-by-default. 

I did extract the whole thing into a plugin. But it's not published yet. 

Only a little change has to be made to the core as mentioned at: https://github.com/Jermolene/TiddlyWiki5/pull/5570#pullrequestreview-722426516

The rest can be handled by the a plugin. ... I'll post a link here, when it's available. 

For your usecase, we would also need a version, which doesn't expose the "external-core" to the users. 

 - If they click the "save button" it will only save the data. .. Done
 - If they click the "download" button, they will download the data + core and get a single-file wiki

**Comment by simonbaird** [comment]
It sounds interesting. Will look forward to reviewing the plugin once it's ready.

For Tiddlyhost downloads I'm thinking about https://sitename.tiddyhost.com/download urls, which would mean the assembly into a standalone empty file would need to happen in Tiddlyhost server side host code also.

**Comment by pmario** [comment]
>For Tiddlyhost downloads I'm thinking about https://sitename.tiddyhost.com/download urls, which would mean the assembly into a standalone empty file would need to happen in Tiddlyhost server side host code also.

That's right. .. But if users create their own buttons, we still need to be sure, that it works.

**Comment by simonbaird** [comment]
https://tiddlywiki.com/#Using%20the%20external%20JavaScript%20template explains it in some more detail. And perhaps the existence of this page indicates that it will continue to be supported.

I'm pretty keen to try to make this work on Tiddlyhost since I expect it reduces the size down to about a quarter. (See [this forum post](https://talk.tiddlywiki.org/t/how-to-reduce-the-size-of-your-tiddlywiki/5364).

**Comment by simonbaird** [comment]
@pmario Am I right to assume this is supported now without a plugin?

**Comment by pmario** [comment]
>@pmario Am I right to assume this is supported now without a plugin?

Yes, it's part of the core now. .. I think it can reduce the amount of content that has to be shipped by the server quite a bit. Most TWs just have a view kBytes of content. So the TW core makes a big portion of the size. 

The core can be cached by the browser which should also improve start speed. AND saving the wiki will also be sped up quite a bit, since the core hasn't to be transferred by the user. 

---------------

With FF there is a bit of a problem if I create the external core-js file. For me FF always adds a `.html` extension to the file, which I have to remove manually. ... But I do have an unpublished PR to fix that.

**Comment by Telumire** [comment]
Hi @simonbaird, I used [a plugin by cdruan](https://github.com/cdruan/tw-external-js) to externalise the core js + plugins of my "libro edition", file size went from 3,24MB to 0,19MB ! Maybe this will be helpful for your investigation : [libro-external-js.tiddlyhost.com](https://libro-external-js.tiddlyhost.com/) vs [libro.tiddlyhost.com](https://libro.tiddlyhost.com/)

**Comment by pmario** [comment]
I do use a test-version at GitHub .. It works well there. https://github.com/pmario/test

**Comment by saqimtiaz** [comment]
> * What about the "download" action, e.g. do we want to optionally support converting an external js TW to a self-contained TW on download by injecting the core plugin?

Having explored externalizing the core in the past, I never used it in practice because I found that users struggled with the shift from a self contained HTML file, to two files that need to be in the same directory (for offline usage). I suspect TH users may have similar issues, in that was it expected when downloading is a self contained and functional TiddlyWiki file.

**Comment by simonbaird** [comment]
> ...expected when downloading is a self contained and functional TiddlyWiki file.

The way I'm picturing it, the core js file will be referenced by an absolute url, i.e. it won't need to be in the same directory as the TiddlyWiki file. This means it would be fully functional, but it would require internet access to work (unless the browser caching was good enough to have the file fully available offline), which is why I'm thinking we might need to explain the difference and provide an option to produce a fully self-contained version when downloading.

**Comment by pmario** [comment]
>This need for internet access is something I think we would need to explain, and perhaps provide an option to produce a fully self-contained version when downloading.

I think it should be possible to create a single file wiki with a TH://index.html?downlad=singlefile.html URI  or even a "download single" button in the wiki

**Comment by simonbaird** [comment]
I'm trying to figure out the best way to produce an external js compatible "empty" file and a matching "tiddlywikicore.js" file. This seems to be pretty close:

```
node tiddlywiki.js editions/server-external-js \
  --verbose --output ./output/external-empty --build index tiddlywikicore
```

Some questions for the experts:
* What's the difference between `$:/core/save/all-external-js` and `$:/core/save/offline-external-js`, and which one would be better for producing an external js "empty" file that could be used on Tiddlyhost, similar to @Telumire's [example](https://tiddlywiki-5-2-4-prerelease-external-js.tiddlyhost.com/)?
* Would the files produced by this command differ from the output from [cdruan's plugin](https://github.com/cdruan/tw-external-js) if used on a fresh empty file, and how?
* Will I run into problems using the "server-external-js" edition's tiddlywiki.info, since I don't actually want to use TiddlyWiki server?

**Comment by cdruan** [comment]
Hi @simonbaird 

> What's the difference between `$:/core/save/all-external-js` and `$:/core/save/offline-external-js`, and which one would be better for producing an external js "empty" file that could be used on Tiddlyhost, similar to @Telumire's [example](https://tiddlywiki-5-2-4-prerelease-external-js.tiddlyhost.com/)?

$:/core/save/all-external-js` is only applicable if you'd like to start up the TW server (node.js) by externalizing the core. E.g.
<pre><code>tiddlywiki YOUR_WIKI_FOLDER --listen 'root-tiddler=<b>$:/core/save/all-external-js</b>' use-browser-cache=yes</code></pre>
It replaces the default root-tiddler  `$:/core/save/all`. So you'd want to use `$:/core/save/offline-external-js` template to produce the .html file. The offline version filters out client/server plugins.

> Would the files produced by this command differ from the files produced with @cdruan's [plugin](https://github.com/cdruan/tw-external-js) if it was used on a fresh empty file?

At this point, the `tiddlywikicore.js` file should be the same; but there are some duplicate code that may become out of sync in the future... (I originally created the plugin to support earlier versions of TW that do not have working external-js functionality, hence the duplicates.)

The actual wiki file (e.g. empty.html) would be different. Wikis produced by the plugin would require/include the plugin either internally or externally. The plugin's saving UI is improved so that a pop-up appears to remind users to download the necessary JS file(s) in addition to the wiki file. The core version only pops up a dialog box to save the wiki. Unfamiliar users will have trouble starting up the wiki if they do not have the required JS file.

> Will I run into problems using the "server-external-js" edition's tiddlywiki.info and build targets, since I don't actually want to use the server with these files?

No, I don't think so.

**Comment by simonbaird** [comment]
Thanks @cdruan, that's really helpful.

**Comment by simonbaird** [comment]
Well, I think it's working pretty well so far. See https://external-core-test.tiddlyhost.com/ for a demo, plus some explanations and warnings.

**Comment by pmario** [comment]
@simonbaird It seems the demo doesn't enable the browser caching mechanism. .. Is that intended, or is there some config missing. 

I'm using Windows 11 and FF 107.0.1 atm.

**Comment by Telumire** [comment]
> Based on [tiddlywiki-5-2-4-prerelease-external-js.tiddlyhost.com](https://tiddlywiki-5-2-4-prerelease-external-js.tiddlyhost.com/)

Thanks for your work and making this official @simonbaird ! Do you want me to delete https://tiddlywiki-5-2-4-prerelease-external-js.tiddlyhost.com now that there is an official solution ?

**Comment by simonbaird** [comment]
I realized that the '$:/core' tiddler can come back as an internal tiddler if it is modified and then the site is saved. I guess it's unlikely someone would modify that, but still, it's a bug. There might be some more work needed here to figure out how to prevent that, perhaps by using the `$:/core/save/offline-external-js` when saving, or by setting '$:/core' to be always readonly somehow. (I'll confess I'm not super clear on how this all works.)

**Comment by simonbaird** [comment]
> Do you want me to delete https://tiddlywiki-5-2-4-prerelease-external-js.tiddlyhost.com now that there is an official solution ?

Up to you, but I'd say let's keep it. The "official solution" is buggy and experimental and also I'm still using your demo as a reference, especially the `$:/config/SaveWikiButton/Template` which I'm having trouble understanding. (How is it a button?)

**Comment by pmario** [comment]
>especially the `$:/config/SaveWikiButton/Template` which I'm having trouble understanding. (How is it a button?)

It's a bot tricky. .. I'll try to explain with the default setting at tiddylwiki.com and then show the difference between tw-com and the external-js 

- The TW [Save Button](https://tiddlywiki.com/#%24%3A%2Fcore%2Fui%2FButtons%2Fsave-wiki) shown in the right sidebar activates the [tm-save-wiki](https://tiddlywiki.com/#WidgetMessage%3A%20tm-save-wiki) message
- tm-save-wiki needs a parameter `param` " Title of a tiddler to use as a template for rendering the wiki" like so:
   - `<$action-sendmessage $message="tm-save-wiki" $param={{$:/config/SaveWikiButton/Template}} filename=<<site-title>>/>`
- So it reads the content of the `{{$:/config/SaveWikiButton/Template}}` tiddler
  - which is: `$:/core/save/all`
- [$:/core/save/all](https://tiddlywiki.com/#%24%3A%2Fcore%2Fsave%2Fall) contains "the recipe" to build `tiddlywiki.html` file
- It does this by defining a filter macro, that's used by the `$:/core/templates/tiddlywiki5.html` template. 

So that's how tiddlywiki.com builds a wiki if the save-button is clicked. 

------------------

Since the external-core version dosn't need the same tiddlers, but also needs to **click the same button** we need a mechanism to "switch" the config. 

- [$:/config/SaveWikiButton/Template](https://tiddlywiki-5-2-4-prerelease-external-js.tiddlyhost.com/#%24%3A%2Fconfig%2FSaveWikiButton%2FTemplate) for the external-js version contains 
- [$:/core/save/offline-external-js](https://tiddlywiki-5-2-4-prerelease-external-js.tiddlyhost.com/#%24%3A%2Fcore%2Fsave%2Foffline-external-js) 
- which looks very similar to `$:/core/save/all` but without the `-[[$:/core]]` and the tiddlyweb related tiddlers` -[[$:/plugins/tiddlywiki/filesystem]] -[[$:/plugins/tiddlywiki/tiddlyweb]]` tiddler. 

So that's the main difference. 

Hope that makes it clearer.

**Comment by pmario** [comment]
>>@Telumire wrote
>>Do you want me to delete https://tiddlywiki-5-2-4-prerelease-external-js.tiddlyhost.com/ now that there is an official solution ?
>
> @simonbaird  wrote
>Up to you, but I'd say let's keep it.

I think you should keep it, since I'm using it for my explanation from the last post too. So we will need it atm.

**Comment by simonbaird** [comment]
Thanks @pmario. It's starting to make more sense.

**Comment by simonbaird** [comment]
I realized the "empty" I created had the highlight-js plugin included for some reason. I've pushed a new version without that, and now a new "external core" site is just 100 KB.

(Still nearly twice the size of FeatherWiki, but 20 times smaller than a TiddlyWiki with `$:/core` included, which is a huge deal for Tiddlyhost.)

**Comment by simonbaird** [comment]
Here's the command I'm using now to create an external-core empty and a core.js:
```
  git reset --hard && git checkout v5.2.3 && \
  node tiddlywiki.js editions/empty --output ../TiddlyWiki5/output/external-core \
    --render '$:/core/templates/tiddlywiki5.js' '[[tiddlywikicore-]addsuffix<version>addsuffix[.js]]' 'text/plain' \
    --rendertiddler '$:/core/save/offline-external-js' 'index.html' 'text/plain'
```

**Comment by simonbaird** [comment]
I would very much like to use `https://tiddlyhost.com/tiddlywikicore-5.2.3.js` instead of `tiddlywikicore-5.2.3.js` for the coreURL.

I think I know how to do it now, but there is an easier way to do it coming in the next release of TiddlyWiki, see [this](https://github.com/Jermolene/TiddlyWiki5/commit/bef11fe6a25fb849dee40c4aa4337d6a30daf0b4).

**Comment by simonbaird** [comment]
Also todo maybe: Make "tw-external-core" a different "kind", separate from "tw5".

**Comment by pmario** [comment]
>Also todo maybe: Make "tw5-external-core" a different "kind", separate from "tw5".

I don't understand that. Can you be more specific?

**Comment by pmario** [comment]
I think it's OK to have a new "kind" .. On the other hand as a user I would expect to be no difference if I want to download a single file wiki. 

There should be a download button, that just does that. In the end I don't really care how the stuff loads from tiddlyhost. It needs to work and the UX should be fast. 

But the most important feature is. I need to trust it. Not about security about **data-integrity**. Content should never be lost. That's it.

**Comment by simonbaird** [comment]
There's a non-trivial number of potential "download" behaviors. Rather than get into it here, I'll make a new issue.

**Comment by simonbaird** [comment]
I think this can be considered done. There is a new "kind" now for the external core TiddlyWiki sites, and there's a unified "core url" for every site (which amplifies the "cache forever" benefits). I moved the "external core" option up the list of options when creating and added some explanations. There might be some follow up work, but I'll make new issues as needed.

Thanks very much @pmario @Telumire @cdruan for the inspiration and technical help.

**Comment by simonbaird** [comment]
> There's a non-trivial number of potential "download" behaviors. Rather than get into it here, I'll make a new issue.

See #283 .

**Comment by simonbaird** [comment]
One more followup: #284 .
