### ISSUE TITLE
URL query string to create wiki from specified url as template?

### ISSUE THREAD

**Issue by saqimtiaz** [simonbaird/tiddlyhost#192]
Would it be possible to extend TiddlyHost to support a query string to specify a TiddlyWiki to use as the template for a new wiki?

Something like `https://tiddlyhost.com/sites/new?template=http://tiddlywiki.com`

There could be a list of allowed URLs that can be used as templates.

Potential use cases:
- Allow users to easily create a copy of an edition (for example https://projectify.wiki/demo.html ) on TiddlyHost
- Allow creating links that when followed, allow the user to create a copy of a wiki on TiddlyHost. Kind of a "fork this wiki" idea.
  - This could be used for example to allow users to easily create a copy of TiddlyWiki.com to then make documentation updates and submit a documentation PR directly from TiddlyWiki. See https://talk.tiddlywiki.org/t/demo-updating-docs-and-creating-a-pr-from-within-tiddlywiki/1285/14
  - If this ever got going we could also ping TiddlyHost when a PR was merged so the associated wiki could be deleted.

**Comment by simonbaird** [comment]
That's a good idea. There's two pieces:
* The url param for /sites/new to preselect which empty to use.
* Adding more interesting empties to use. (Currenly there are three: tw5, classic, and tw5-prerelease.)

**Comment by simonbaird** [comment]
I checked projectify and its empty is still 5.1.23, which is a little inconvenient since I'd want to only use 5.2+ empties if I can.

**Comment by simonbaird** [comment]
Three pieces:
* Allow creating a new site as a copy of an existing (public) site.

I'm less sure of that one since it implies a level of trustworthiness that might not be appropriate.

**Comment by saqimtiaz** [comment]
> * Allow creating a new site as a copy of an existing (public) site.
> 
> I'm less sure of that one since it implies a level of trustworthiness that might not be appropriate.

Right, which is why I suggested a whitelist of domains from which this would be allowed, for example:
```
tiddlywiki.com/*
tiddlyhost.com/*
```
I am thinking of options like creating a copy of tiddlywiki.com, which would be very useful if possible but would probably not be relevant to most users and would clutter the select dropdown.

**Comment by simonbaird** [comment]
Looks like Projectify is currently abandoned :( https://github.com/NicolasPetton/Projectify .

**Comment by saqimtiaz** [comment]
Unfortunate, it was one of the most polished TW5 editions that I have seen. However, it should still be perfectly useable with 5.2.0 if someone were to create an updated empty starter file.

**Comment by simonbaird** [comment]
Reading this again I noticed I was focussed on the new user experience where we'd want a smaller, heavily curated list of trusted "editions" or "flavors". Now I realize your use case is more about a power user who just wants to save the manual steps required to create a site, download the desired TW file, then upload that file to the new site.

That does seem like a reasonable idea. In general I guess I tend to be less interested in the UX for power users, since I figure they're probably capable of figuring out alternative solutions anyhow.

**Comment by saqimtiaz** [comment]
@simonbaird my request was indeed not directly intended for new users of TiddlyHost that create a new wiki through the intended UX.

However, such a facility would allow others that create editions to make it easier for new users to create a copy of a wiki on TiddlyHost by providing a URL with the correct query. The end goal is indeed to make life easier for new users, and to enable collaborative workflows where a wiki can be easily be forked, changes made and then potentially pulled back in.

**Comment by twMat** [comment]
> Would it be possible to extend TiddlyHost to support a query string to specify a TiddlyWiki to use as the template for a new wiki?
> 
> Something like `https://tiddlyhost.com/sites/new?template=http://tiddlywiki.com`

I like this. A more friendly UI could be a feature on (e.g) the "Your sites" page, showing an empty field where the user fills in the url where to fetch a wiki from and an OK button.

...and if you allow me to go off on a tangent: If instead a permalink is added, i.e an url to specific tiddlers in a wiki, then maybe only those tiddlers could be fetched? This touches on Jeds and my experiments with TWederation. This would enable people to communicate with one another via TW because permalinks allow for *filters* so you could filter for e.g all tiddlers tagged @simonbaird or @saqimtiaz ... and you could "subscribe" to wikis by having a predefined list of wikis that you do this fetching from. Another use if specific tiddler imports were possible would be to *update* plugins!

(Inappopriate thread jacking? I figure this is a very small forum so I take more liberties here but do tell me if this is not appreciated :)

Anyway, great ideas in this thread.

**Comment by simonbaird** [comment]
Reiterating what I said above. I see this is quite separate from #207.

This is a power user feature for people who know what they're doing, and can make their own decisions about stability and trustworthiness of the source empty, whereas #207 is something for non-power users to be introduced gently to some carefully curated TiddlyWiki variants.

**Comment by simonbaird** [comment]
Here's a new implementation idea:

* If you (as site owner) want to make your site cloneable by others, list it in a the hub and configure it "make cloneable" option.
* Other signed in users, when browsing the hub will now see a clone button on that cloneable site. Also there would be a hub filter option to show only cloneable sites.

**Comment by simonbaird** [comment]
Maybe the cloning support and the shared cloneable template system has achieved the objectives of this request, albeit in a different way.

I think the subset of users who would want to be able to create from an abitrary url now is small, so I'll probably close it soon.
