### ISSUE TITLE
Add subdomain based "spaces" for sites

### ISSUE THREAD

**Issue by simonbaird** [simonbaird/tiddlyhost#22]
At the moment, anyone can have any site name, but maybe it would be better if there were "spaces" owned by one user, where you could choose a site name without it clashing with existing sites. It wouldn't be a proper subdomain in dns terms, but the "domain labels with dots" idea that used to work fine for Tiddlyspot. (Currently Tiddlyhost deliberately disallows '.' chars in the site name.)

E.g. notes.simon.tiddlyhost.com, aboutme.simon.tiddyspot.com

Only the owner of the space would be allowed to create sites in that space.

It would be possible to rename your space (I guess), and move sites to and from a space.

**Comment by twMat** [comment]
Is the point here to avoid name-napping (*"Yes, I staked sex.tiddlyhost.com first!"*)?

Related:
I don't know what people used TS for but I would guess a majority of the wikis were either personal/private wikis or they were "TW community" wikis e.g to distribute plugins. IF this is the case, then I think it makes sense with this format:

`matias.tiddlyhost.com/foo`

because it is at least a tad simpler to work with a suffix like this, programmatically, in TW. It also makes for easier and neater overview if there's a long list of such URLs. Varying prefix make such lists "uneven" and it is harder to spot odd titles in the listing. (Tell me if it is unclear what I mean, becaues this is IMO this is rather important detail... for those rare occasions)

Beyond these aspects I don't feel it makes much difference with such per-user namespaces as opposed to how it was in TS. Others may have more insights/opinions.

**Comment by kookma** [comment]
I support @twMat idea! This way one can find all plugins from example published by matias!

**Comment by simonbaird** [comment]
This doesn't really solve ambitous squatters grabbing 'sex.tiddlyhost.com'. Not sure what we can do about that, but maybe it won't be a big problem.

There are some non-trivial considerations, e.g. if some creates a site, "thing.tiddlyhost.com", then does the namespace "thing" become unavailable? Similarly if someone creates the namespace *.thing.tiddlyspot.com, does the corresponding site become unavailable?

Or.. could foo.thing.tiddlyspot.com and thing.tiddlyspot.com be unrelated and owned by different users? That would work fine I think, but maybe it's confusing.

I guess I've decided that I don't want to force every site to have a namespace. E.g. mptw.tiddlyspot.com is better than, mptw.simon.tiddlyspot.com. But I still like the idea of notes.simon.tiddlyspot.com, ideas.simon.tiddlyspot.com, about.simon.tiddlyspot.com etc, where I could own the entire *.simon.tiddlyspot.com namespace.

Ps, the url for a list of all your (searchable public) sites would probably be more like `tiddlyhost.com/user/matias` because anything with a subdomain is a TiddlyWiki site. You'll have to deal with uneven lists.

**Comment by simonbaird** [comment]
I realize there might be some impact on the wildcard SSL certs. Apparently (to be confirmed?) you can't easily do *.*.domain.com wildcard certs, so *.simon.tiddlyhost.com for example would need to be specifically listed in the cert. doesn't scale well if we're handing out spaces for everyone.

**Comment by simonbaird** [comment]
This one's on hold for now.

**Comment by simonbaird** [comment]
This idea is likely to be superseded by #145.

**Comment by simonbaird** [comment]
Replaced by #145 .
