### ISSUE TITLE
How to revert save button functionality to download the wiki?

### ISSUE THREAD

**Issue by wccbuck** [simonbaird/tiddlyhost#256]
The save button on my wiki used to download the page locally, just like the feature behaves on tiddlywiki.com. At some point in the past (I can't seem to find reference to it in the commits), this feature changed to upload wiki changes if the owner clicks the button, and throw an error otherwise. This is not useful to me, and I would much prefer the button exhibit the old behavior. How can I do this?

**Comment by wccbuck** [comment]
I figured it out. Edit the shadow tiddler titled "$:/core/modules/savers/download.js" and change the priority to 10000. It's really obnoxious that I have to overwrite a shadow tiddler to do this but I know it's not tiddlyhost's fault. Thank you

**Comment by simonbaird** [comment]
A couple of notes:
* There's two ways to download the latest version of your site. Firstly you add `/download` to the end of the url, and secondly you can use the "Actions" menu for your site on Tiddlyhost home page and click "Download".
* There's no easy way do that from the TiddlyWiki file currently because generally you want to make sure that the Tiddlyhost site is always up to date with the latest changes. If you always save locally then Tiddlyhost is not going to be very useful. When you come back to your site on Tiddlyhost the changes you save locally won't be there.

So because of point two, I'm not sure I understand why you want to have the save button do a download save.

**Comment by simonbaird** [comment]
If you do understand all that and just want a convenient download link within your TiddlyWiki, there's some examples of how you can do it [here](https://simon.tiddlyhost.com/#Download%20links%20%26%20buttons:%5B%5BDownload%20links%20%26%20buttons%5D%5D%20%5B%5BDownload%20button%20demo%5D%5D).

**Comment by wccbuck** [comment]
Thank you for the replies. To clarify my use case, my tiddlywiki is eberron.tiddlyhost.com, which is a tabletop RPG notebook that I share with others so that they can build on what I've done for their home games. Since I work on the document locally using node.js and maintain a github for it, and since there is already an upload process for updating the hosted tiddlywiki, complete with an "are you sure" prompt, I have no need for the save button to duplicate that functionality.

**Comment by simonbaird** [comment]
Ah, ok, that does make sense. Thanks for the explanation. That is an interesting use case and a workflow that I had not thought of. (Even so, you might still want to consider trying one of the other download methods, or at least be aware they are an option.)
