### ISSUE TITLE
Feature request: Support tiddlywiki 5.3.0!

### ISSUE THREAD

**Issue by ejheil** [simonbaird/tiddlyhost#310]
We've got an exciting new release out there, I'd love to be able to use it on Tiddlyhost!

**Comment by simonbaird** [comment]
It's done already, go to https://tiddlyhost.com/sites/new and you should see 5.3.0 available.

Note that you need to upgrade your existing sites manually, see https://github.com/simonbaird/tiddlyhost/wiki/Upgrading-your-site-to-the-latest-version-of-TiddlyWiki for details on how to do that.

(FYI, the 5.3.0 roll out was slightly delayed due to https://github.com/flibbles/tw5-uglify/issues/8 which impacts the external core version.)

**Comment by ejheil** [comment]
Awesome, thanks so much!

**Comment by flibbles** [comment]
uglify has caught up enough that it can function with v5.3.0. It doesn't know how to compress any new features optimally, but it won't break them.
