### ISSUE TITLE
error code '418 Invalid TiddlyWiki' for my TiddlyWiki 5.3.0

### ISSUE THREAD

**Issue by Rayme** [simonbaird/tiddlyhost#316]
It works somewhere else but not on TiddlyHost https://bionic-cats.tiddlyhost.com , for example https://jefftay.com (node.js version) and https://wiki.imzm.im (single HTML version)

I tried upload and cover old one and drag into the old one, but I get this 418 error.

**Comment by simonbaird** [comment]
The problem is due a a missing close div tag in `LoadingSplashScreen`. At the very end of the `LoadingSplashScreen` tiddler, if you add one more `</div>` it will closes the opening `<div class="tc-remove-when-wiki-loaded">` div element. Then if you save the TiddlyWiki, the result should work correctly on Tiddlyhost.

This problem is discussed at #311.

**Comment by Rayme** [comment]
> 

Thanks Simon, this solves the problem immediately. You're awesome! and TiddlyHost too
