### ISSUE TITLE
RawMarkup tag in a tiddler, ends in palette errors when use external core TiddlyWiki

### ISSUE THREAD

**Issue by leoperbo** [simonbaird/tiddlyhost#317]
Okay, cool.

FWIW, I think an "external core" TiddlyWiki would be small enough to be under Mastodon's 1MB site threshold.

_Originally posted by @simonbaird in https://github.com/simonbaird/tiddlyhost/issues/264#issuecomment-1382862443_

**Comment by leoperbo** [comment]
I just accomplished distributed verification between my Mastodon profile and an external core TiddlyWiki hosted in Tiddlyhost, thanks for the suggestion.

Now, I have the problem described in the title of this issue: RawMarkup tag in a tiddler, needed for the rel="me" code to work, ends in palette errors when use external core TiddlyWiki. 

This is a screenshot from https://tiddlyblog.tiddlyhost.com/ there is a tiddler tagged with `$:/tags/RawMarkup`:

![Screenshot 1](https://cloud.disroot.org/s/L72qHE59rkxPFgZ)

And this is a screenshot from a local version (no external core) of the same TiddlyWiki, with the tiddler tagged with `$:/tags/RawMarkup`,:

![Screenshot 2](https://cloud.disroot.org/s/z9dTS8koNfZexMT)

If I remove the tiddler tagged with `$:/tags/RawMarkup`, the palette in https://tiddlyblog.tiddlyhost.com/ renders ok, but I loose distributed verification.

**Comment by simonbaird** [comment]
Let me see if I can figure out what's going on.

**Comment by simonbaird** [comment]
So the palette problem is fixed by adding a class to the body element called `tc-body`. I'm not sure exactly why it's missing though.

**Comment by simonbaird** [comment]
I haven't confirmed this, but I think what you need to do is change the tag in the `$:/twl/relme` tiddler to `$:/tags/RawMarkupWikified/TopBody` instead of `$:/tags/RawMarkup` so the raw content lands inside the `body` element instead of inside the `head` element.

Alternatively you could use the "link" form of the link, e.g. `<link href="https://social.example.com/@username" rel="me">`, which should work fine inside the `head` element.

**Comment by leoperbo** [comment]
Yes! Both directions works flawlessly, and I'll keep the second one.
Thank you!
