### ISSUE TITLE
add filter to the hub for type of wiki

### ISSUE THREAD

**Issue by VikingMage** [simonbaird/tiddlyhost#321]
Hi Simon

* Feature suggestion for the tiddlyhost hub.
* I think it would be nice & handy if we could filter searches by specific wiki flavour.
   * eg tiddlywiki 5, tiddlywiki classic & feather wikis
* possibly even between major releases of tiddlywiki
   *  eg 5.0, 5.1, 5.2, 5.3

**Comment by simonbaird** [comment]
Great idea!

**Comment by simonbaird** [comment]
Done via 4a051cf216a74431030720f404df3a1153194e4c .

For the releases, instead of doing a filter I added extra sorting options, called "oldest version" and "newest version", see 5d2cedadd10d180ae8419f023818aa8153dc65c0 . Filtering by version could still be done in the future, but perhaps sorting is good enough.

**Comment by simonbaird** [comment]
I'm calling the type of wiki "kind". See the "Kind" option visible in the hub.

For example, here are the TiddlyWiki Classic sites in the hub: https://tiddlyhost.com/hub?k=classic .
