### ISSUE TITLE
Store sites compressed or gzipped

### ISSUE THREAD

**Issue by simonbaird** [simonbaird/tiddlyhost#43]
Should cut down total size considerably, which might reduce S3 costs.

**Comment by simonbaird** [comment]
I didn't think of it before, but if the "apply_mods" was before save instead of before serve, maybe the gzipped content could be served directly, with suitable headers so browsers know what to do with it.

**Comment by saqimtiaz** [comment]
@simonbaird if content can be served with gzip without incurring a unreasonable server load that would be helpful indeed. It probably doesn't matter for the majority of users but there are still those in bandwidth scarce areas for whom the over 3MB size of a TiddlyWiki can be an issue. 

However at this time I would classify this as something nice to have rather than something urgent or essential.

**Comment by pmario** [comment]
If you store the wikis in a compressed format, you will have the advantage, that the storage and the transfer is optimized. 

On the other hand it needs more server-CPU cycles if you want to send the tiddlers.json format, because the server has to unpack the wiki -> extract the JSON data -> send it to the client. 

IMO some calculations should be made, to see the pros and cons

**Comment by saqimtiaz** [comment]
Also worth keeping in mind that the JSON end points will most likely be requested far less frequently than the HTML files.

**Comment by pmario** [comment]
> Also worth keeping in mind that the JSON end points will most likely be requested far less frequently than the HTML files.

At the moment, this may be true. .. But who knows, if the "JSON sharing" stuff will get popular in the future. ... 

I know, that server side disk space is cheep compared to CPU cycles and RAM. ... So if the service becomes popular, vertically scaling the VM will probably be a cost factor too.

**Comment by pmario** [comment]
@simonbaird ... How does your backup-strategy look atm? ... It will also contribute to the HD size needed.

I've had a really short look at the code. But I'm not familiar with ruby. ...

**Comment by simonbaird** [comment]
So far there's 1.6G in S3, but gzipped it's around 0.5G.

I'm not sure how S3 billing works, but I think maybe the number of reads and writes is more, or at least as significant that the total size. Hence #44 might be more impactful overall.

**Comment by simonbaird** [comment]
Re backups, currently there aren't any. See #74.
