### ISSUE TITLE
Support Tiddlywiki Classic

### ISSUE THREAD

**Issue by simonbaird** [simonbaird/tiddlyhost#78]
I want to consider the migration path for long-time Tiddlyspot users, many of which are using Classic aiui.

There's a few considerations such as what empty to use, how do we ensure the upload plugin is present, etc.

I guess we could support this only for uploaded sites, see #77, but I feel like we should do it properly and make TW Classic a first class citizen on Tiddlyhost.

**Comment by simonbaird** [comment]
I'm interested in opinions about TW Classic. Should we discourage its use? Or should we treat it like a respected alternative to TW5? @twMat @jermolene any thoughts?

**Comment by Jermolene** [comment]
Hi @simonbaird as far as policy goes, I've tried to treat TiddlyWiki Classic as a first class citizen in all of the things that I've built around TW5. First TiddlyFox, TiddlyDesktop and more recently the work I've been doing on [Fission](fission.codes). (In fact, the first functionality of TW5 was to cook TWC from its raw files). All of this is partly out of wanting to respect TWC users, but also because I enjoy the challenge of seeing how long we can keep TWC alive.

**Comment by simonbaird** [comment]
Cool, thanks. I like that answer. :)

**Comment by twMat** [comment]
I guess you guys won't like my answer then; As an *end user* who has migrated fully to TW5, I find TWC to be a distraction. There is a steady and recurring confusion from people on the boards who ask about some problem and it turns out they have the versions confused (and this can cause confusion for *everyone* in the discussion, not just the one asking). While it'd be fair with a migration path from TS to TH also for TWC, and capabilities to host TWCs on TH, I personally don't think *new* users should be encouraged to use it.

**Comment by AndrewMcNZ** [comment]
I would very much like to have TW Classic on Tiddlyhost. I have a long-time TWc that was on Tiddlyspot that works the way that I want and has a setup that I cannot duplicate on TW5. Hower, I also agree with @twMat that users should be encouraged to begin new TiddlyWikis using TW5 rather than TW Classic.

**Comment by simonbaird** [comment]
Closed via #82 , but see #83.
