### ISSUE TITLE
Offer a selection of editions for new wikis

### ISSUE THREAD

**Issue by Jermolene** [simonbaird/tiddlyhost#81]
It would be helpful to be able to offer users a selection of empty editions when creating a new wiki, each consisting of a particular core version with a selection of plugins and configuration tiddlers.

I've been starting to explore what would be involved in maintaining an official catalogue of editions in the work on TiddlyWiki on Fission. There's a simple [script](https://github.com/Jermolene/tiddlywiki-on-fission/blob/main/bin/collect-editions.js) that loads up a folder of templates from a [configuration file](https://github.com/Jermolene/tiddlywiki-on-fission/blob/20e25374080d43fddcd10c1a864e98d0d314e6bb/editions/bill-of-materials.json)

```json
[
	{
		"name": "tiddlywiki.com",
		"description": "~TiddlyWiki 5 latest release",
		"url": "https://tiddlywiki.com/empty.html"
	},
	{
		"name": "tiddlywiki.com-prerelease",
		"description": "~TiddlyWiki 5 prerelease of the next version",
		"url": "https://tiddlywiki.com/prerelease/empty.html"
	}
]
```

The build process is run by GitHub actions, which is happy to run Puppeteer, so we get screenshots generated for each edition:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/174761/110256091-e3458600-7f8e-11eb-82bb-023af2d21a0c.png">

If there's interest, we could move the editions stuff to its own GitHub repo, and make it official so that it can be more easily included in other projects.

**Comment by simonbaird** [comment]
Nice.

There's some wip code [here](https://github.com/simonbaird/tiddlyhost/compare/uploads-and-classic-support) to support selecting a different empty when creating a site. Initially the choices are TW5 and Classic, but the idea of providing stable and prerelease TW5 is something I want to do soon. Offering pre-packaged "flavours" the way Tiddlyspot used to do is also on the cards for later.

Ps, the screenshots are a nice touch. I'd like to incorporate those, and maybe figure out how to generate them as per #69.

**Comment by Jermolene** [comment]
> There's some wip code [here](https://github.com/simonbaird/tiddlyhost/compare/uploads-and-classic-support) to support selecting a different empty when creating a site. Initially the choices are TW5 and Classic, but the idea of providing stable and prerelease TW5 is something I want to do soon. Offering pre-packaged "flavours" the way Tiddlyspot used to do is also on the cards for later.
> 
> Ps, the screenshots are a nice touch. I'd like to incorporate those, and maybe figure out how to generate them as per #69.

Great, it looks like your code is doing roughly the same thing, minus the Puppeteer stuff (which is actually pretty easy).

I'd like to try to agree a standard format for the edition metadata. It would also be helpful for users if we could establish a single central registry of editions that anyone can make PRs to.

That repo could also have a cron job to grab changes to editions, keeping the retrieved files in the repo, so that apps like 
TiddlyHost or TiddlyWiki-on-Fission could just grab the editions direct from the repo, without having to do the HTTP retrieval, or Puppeteer stuff.

**Comment by simonbaird** [comment]
For the record, https://github.com/simonbaird/tiddlyhost/pull/82 is where that wip link ended up.

**Comment by Jermolene** [comment]
> Where can non-current empty file versions be downloaded? I know about https://github.com/Jermolene/TiddlyWiki5/releases , but I just want an empty.html, not the entire source repo, i.e. something like https://classic.tiddlywiki.com/archive/ .

There's a bit of a black hole there for us at the moment. https://github.com/Jermolene/jermolene.github.io has a full history, but doesn't have release tags. So I have a horrible feeling that reconstructing an archive of old TW5 versions would require crawling the repo history to detect the first index.html with each successive version number.

**Comment by simonbaird** [comment]
Never mind, it's not too important.

I might start checking in empty files to the tiddlyhost git repo once there are multiple versions.

(That does sound like a fun script though.. :)

**Comment by simonbaird** [comment]
FYI I'm now checking in different empty versions, see https://github.com/simonbaird/tiddlyhost/tree/devel/rails/tw_content/empties/tw5 , but they're only for testing purposes. When creating a site the only options are the latest stable TW5, the prerelease TW5, and the latest Classic. You have to click "Advanced options" to expose the selector, otherwise you get the default.

**Comment by simonbaird** [comment]
The latest pre-release is fetched automatically pretty regularly, but it takes a commit and a deploy to update the stable version. That could change in future - maybe automatically fetching the latest stable version is a good idea.

**Comment by offray** [comment]
Regarding a selection of TW templates (we call them seeds) the admin GUI could offer a URL field for the starting template. So it will download the TW file from there and use it as a base for a new wiki. 

For the moment, what we are doing is downloading a starting seed/template from our customized TWs and then upload it from the PC to a newly created wiki, overwriting it. But the process seems pretty indirect.

BTW, thanks for TW. It has been the best onboarding experience for new TW users in several grassroots workshop and university courses I have had so far (as pointed in the forum)

**Comment by simonbaird** [comment]
Here's an idea I've been toying with:
* In Tiddlyhost's site settings there could be a checkbox for "Use as template for new sites (for yourself)".
* If you check that then a new option appears when creating a site to use that as an empty instead of the default empty.

Taking it one step further:
* In Tiddlyhost's site settings add a checkbox for "Use as template for new sites (for everyone)"
* Now the edition appears for anyone creating a new site, not just you.

The second part raises concerns of trust IMO, since anyone using that empty is trusting that its creator is not a hacker trying to steal their passwords or bank details. To deal with that I would either put a large warning "Do not use this empty file unless you trust its creator!", or think of some other way to review or vet the edition before allowing it to be avilable to others.

**Comment by simonbaird** [comment]
I would still like to add some interesting editions directly, but I'm not sure I know any. Looking at https://talk.tiddlywiki.org/t/the-essential-editions-of-tiddlywiki/3347 it seems like the idea is to invent some rather than point to existing options.

**Comment by offray** [comment]
> Here's an idea I've been toying with:
> 
>     * In Tiddlyhost's site settings there could be a checkbox for "Use as template for new sites (for yourself)".
> 
>     * If you check that then a new option appears when creating a site to use that as an empty instead of the default empty.

I like this idea better.

> I would still like to add some interesting editions directly, but I'm not sure I know any. Looking at https://talk.tiddlywiki.org/t/the-essential-editions-of-tiddlywiki/3347 it seems like the idea is to invent some rather than point to existing options.

Maybe an issue template in GH could be offered so, the TiddlyHost community can point to TW templates to be used by other users. I think it could grow organically. 

At least in my case, I point consistently to TiddlyHost as the default and more fluent online onboarding TW experience for my students and workshops and to Timimi as the offline one. Despite of being the best offline saver I have tested so far, I may replace Timimi with the time, with something simpler, inspired by [TW5 SERVER](https://github.com/korikori/tw5_server), but made in [Nim](https://nim-lang.org/), because local teaching experiences have shown that it has too moving parts for non-technical audiences (different installers for several OS and several web browsers combinations, plus enabling them in different ways in such OS).

Anyway I think that TiddlyHost plays an important role and helping to improve it with our feedback as users, is a net gain for the whole TW community, even if other options exists. The idea of community templates is a way to bridge TiddlyHost strengths with the community editions.

**Comment by simonbaird** [comment]
If we were going to start out with one or two editions to add alongside the Release/Prerelease/Classic do you have a suggestion for what they could be?

**Comment by simonbaird** [comment]
Superseded by the "templates" concept which lets community members maintain are support their own editions.
