### ISSUE TITLE
Hub sites could be bootstrap cards

### ISSUE THREAD

**Issue by simonbaird** [simonbaird/tiddlyhost#89]
https://getbootstrap.com/docs/4.6/components/card/

See also #69

**Comment by twMat** [comment]
I'll just mention a concept that @inmysocks and I first developed; The idea is a tiddler that serves as a kind of "business card" (remember those), i.e a tiddler with the unique identifier for a TW (e.g the unique URL or some other identifier). The idea is that it is easy to share such tiddlers and that other meta data can be added to it, including "pretty" content such as if the ower wants to present him/herself. A wiki that presents e.g a plugin could present information about the plugin there. We called the concept twCards and it provides a concrete manifestation to manipulate "wikis" inside wikis. Actually, fellow @MarxSal and I just release a plugin for importing "rows into tiddlers" from Google Sheets that uses this concept. There we call them SpreadsheetTiddlers, see [bottom tiddler here](https://marxsal.github.io/TiddlyGoo/#DEMO%20spreadsheet:About%20%5B%5BDEMO%20spreadsheet%5D%5D).

I don't know what you have in mind for "hub sites" but one idea would be to use something like twCards that people can basically pick up and put in their own wikis so they have a link to the site. Why? Well, for example, currently plugins are titled `$:/plugin/JohnDoe/ThePlugin`. A twCard could provide a list of JohnDoes plugins and sites, to name one example. It could contain version numbers so that a user who gets an updated twCard is alerted about installed plugins that are outdated.

Or maybe my rambling is totally irrelevant ;-)

**Comment by simonbaird** [comment]
I like the idea that Tiddlyhub can produce raw data like this for consumption in interesting ways.

Suppose /hub/user/Matias/info.json was some JSON data that you (or anyone) could slurp up and do things with. To begin with it could include a list of hub sites, and maybe later a list of plugins in those sites. I don't think Tiddlyhost wants to be opinionated about the format, but I'd imagine the data could provided in whatever format is useful.

Ps, you should start by setting a username - currently you don't have a hub url since you have no username.

**Comment by simonbaird** [comment]
This discussion is off-topic for this particular issue though. I'm just talking about using some Bootstrap styles. :)

**Comment by twMat** [comment]
Off topic

>Ps, you should start by setting a username - currently you don't have a hub url since you have no username.

Thanks! On https://tiddlyhost.com/users/edit , the only thing that is mentioned about setting a username is that it is optional - no mention of getting a "hub url" nor what a "hub url" is. (BTW, a reason for me to *not* normally set "usernames" is that on some sites I'm then expected to remember what name I used when I log in which I rarely do...)

**Comment by simonbaird** [comment]
I revamped the html/css recently (with the thumbnail support) and I did briefly try using bootstrap cards. In the end I didn't use them. Close/wontfix.
